GET http://localhost:5000/laporan

###
GET http://localhost:5000/laporan_pembimbing

###
GET http://localhost:5000/laporan_pembimbing/631365b68384acef7a3c933b

###
GET http://localhost:5000/laporan/6305cf04990b5822ba7091e0

###

POST http://localhost:5000/laporan
Content-Type: application/json

{
    "id_user" : "631023359ec61d81924f0861",
    "nama_user" : "asdzxc",
    "tanggal_laporan" : "2022-08-28",
    "isi_laporan" : "whatever"
}
###
GET http://localhost:5000/laporan_user/631023359ec61d81924f0861


###

PATCH http://localhost:5000/laporan/6305cf04990b5822ba7091e0
Content-Type: application/json

{
    "id_user" : "999",
    "nama_user" : "999",
    "tanggal_laporan" : "2022-08-28",
    "isi_laporan" : "whatever"
}

###

DELETE http://localhost:5000/laporan/6305cf04990b5822ba7091e0
Content-Type: application/json


### PRESENSI
GET http://localhost:5000/presensi

###
GET http://localhost:5000/presensi_detail

###
GET http://localhost:5000/presensi_detail/631365b68384acef7a3c933b

###
GET http://localhost:5000/presensi_user/630b5ee09bcc417e95c36864


###
GET http://localhost:5000/presensi_today/630f6f5d6b70943b9b7dd7ce

###
POST http://localhost:5000/presensi
Content-Type: application/json

{
    "id_user" : "3",
    "nama_user" : "rraar",
    "waktu_absensi" : "2022-08-27",
    "keterangan" : "Hadir"
}

###
DELETE http://localhost:5000/presensi/630f6f5d6b70943b9b7dd7ce
Content-Type: application/json


### USER
GET http://localhost:5000/user

### USER
GET http://localhost:5000/user/630c92633929b53750a6f68d

### USER
GET http://localhost:5000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzEzNjVlNzgzODRhY2VmN2EzYzkzNTAiLCJuYW1hIjoiNDMyMSIsImVtYWlsIjoiNDMyMSIsImlhdCI6MTY2MjI2OTgxNiwiZXhwIjoxNjYyMjY5ODQ2fQ.1Kfs5KFKm2h9ZTvOqmOG0U4q0ZPgZ1RU-QLtkP4rtwo

###
POST http://localhost:5000/user
Content-Type: application/json

{
    "email" : "rick2y@ricky.com",
    "nama" : "Ricky Aditya Bagaskara",
    "asal_instansi" : "Universitas Pakuan",
    "role" : "user",
    "tanggal_mulai" : "2022-08-27",
    "tanggal_selesai" : "2022-08-29",
    "tanggal_selesai" : "2022-08-29",
    "password" : "123",
    "confPassword" : "123"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "4321",
    "password": "4321"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout






###
DELETE http://localhost:5000/user/630b2d15a3ad70248819a6a8
Content-Type: application/json